<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            'Programming',
            'Management',
            'Design',
            'Marketing',
            'Sales',
            'Customer Support',
            'Finance',
            'Human Resources',
            'DevOps',
            'Data Science',
        ];

        foreach ($categories as $name) {
            // firstOrCreate checks by name; slug is auto-generated by the Category model's creating event
            Category::firstOrCreate(['name' => $name]);
        }
    }
}
